apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    helm: {}
    repoURL: 'https://github.com/giovanni-colognesi/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: main
    path: giropops-senhas/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: giropops-senhas
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true