apiVersion: argo-cd.argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
    project: default
    sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 9.2.2
      chart: grafana
      helm:
        valueFiles:
        - $values/grafana/values.yaml
    - repoURL: 'https://github.com/giovanni-colognesi/descomplicando-gitops-no-kubernetes-argocd.git'
      targetRevision: main
      ref: values
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: monitoring
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true