# Chart.yaml
apiVersion: v2
name: prometheus
description: A Helm chart for prometheus
version: 0.1.0
dependencies:
  - name: prometheus
    version: 15.7.1
    repository: https://prometheus-community.github.io/helm-charts
