apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
      - git:
          repoURL: https://github.com/giovanni-colognesi/descomplicando-gitops-no-kubernetes-argocd.git
          revision: main
          directories:
            - path: applicationset/apps/*/helm
      - git:
          repoURL: https://github.com/giovanni-colognesi/descomplicando-gitops-no-kubernetes-argocd.git
          revision: main
          pathParamPrefix: cfg
          files:
            - path: applicationset/configs/dev.json
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-{{cluster.nome}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/giovanni-colognesi/descomplicando-gitops-no-kubernetes-argocd.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true




